name: React Build & Deploy to S3 and EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload dist to S3
        run: aws s3 sync dist/ s3://my-react-deploy-bucket --delete

      # NEW STEP: Trigger EC2 to pull from S3
      - name: Deploy to EC2 from S3
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Syncing from S3 to EC2..."
            aws s3 sync s3://my-react-deploy-bucket /home/brewpost/brewpost/dist --delete
            
            echo "Fixing permissions..."
            sudo chown -R ubuntu:ubuntu /home/brewpost/brewpost/
            sudo chmod -R 755 /home/brewpost/brewpost/
            
            echo "Verifying files..."
            ls -lh /home/brewpost/brewpost/dist/index.html
            
            echo "Testing Nginx config..."
            sudo nginx -t
            
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            
            echo "Deployment complete!"