name: React Build & Deploy to S3 and EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload dist to S3
        run: aws s3 sync dist/ s3://my-react-deploy-bucket/frontend --delete

      - name: Upload server files to S3
        run: aws s3 sync . s3://my-react-deploy-bucket/server --exclude "dist/*" --exclude "node_modules/*" --exclude ".git/*" --delete

      - name: Trigger EC2 update via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/brewpost/brewpost",
              "aws secretsmanager get-secret-value --secret-id env --query SecretString --output text > .env",
              "rm -rf /home/brewpost/brewpost/dist/*",
              "aws s3 sync s3://my-react-deploy-bucket/frontend /home/brewpost/brewpost/dist --delete",
              "aws s3 sync s3://my-react-deploy-bucket/server /home/brewpost/brewpost --exclude dist/* --exclude node_modules/* --delete",
              "npm install --omit=dev",
              "pkill -f unified-server || true",
              "sleep 2",
              "PORT=8080 nohup node unified-server.js > server.log 2>&1 &",
              "sleep 3",
              "sudo chown -R ubuntu:ubuntu /home/brewpost/brewpost/",
              "sudo systemctl reload nginx"
            ]' \
            --region ${{ secrets.AWS_REGION }} \
            --query 'Command.CommandId' \
            --output text)
          
          echo "Command ID: $COMMAND_ID"
          echo "Waiting for command to complete..."
          
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
            --region ${{ secrets.AWS_REGION }}
          
          echo "Command completed successfully!"